#!/bin/bash
set -euo pipefail

# ─── Le Chroniqueur — One-command installer ───

REPO="PowerGlove/LeChroniqueur"
BRANCH="main"
RAW_URL="https://raw.githubusercontent.com/${REPO}/${BRANCH}"
INSTALL_DIR="lechroniqueur"

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[0;33m'
NC='\033[0m'

echo -e "${BLUE}"
echo "  _           ____ _                      _                       "
echo " | |    ___  / ___| |__  _ __ ___  _ __ (_) __ _ _   _  ___ _ __ "
echo " | |   / _ \| |   | '_ \| '__/ _ \| '_ \| |/ _\` | | | |/ _ \ '__|"
echo " | |__|  __/| |___| | | | | | (_) | | | | | (_| | |_| |  __/ |   "
echo " |_____\___| \____|_| |_|_|  \___/|_| |_|_|\__, |\__,_|\___|_|   "
echo "                                               |_|                 "
echo -e "${NC}"
echo -e "${BLUE}Installation self-hosted${NC}"
echo ""

# ─── Check prerequisites ───
check_command() {
  if ! command -v "$1" &> /dev/null; then
    echo -e "${RED}Erreur: $1 n'est pas installe.${NC}"
    exit 1
  fi
}

check_command docker
check_command curl
check_command openssl

# Check Docker Compose
if ! docker compose version &> /dev/null; then
  echo -e "${RED}Erreur: Docker Compose v2 n'est pas installe.${NC}"
  exit 1
fi

echo -e "${GREEN}Prerequis OK${NC} (docker, curl, openssl)"
echo ""

# ─── Collect information ───
echo -e "${YELLOW}Configuration :${NC}"
echo ""

# 1. Discord Token
echo -e "${BLUE}1/4${NC} Token du bot Discord"
echo "    Obtenir sur : https://discord.com/developers/applications > Bot > Token"
read -rp "    Discord Bot Token: " DISCORD_TOKEN
while [[ -z "$DISCORD_TOKEN" ]]; do
  echo -e "${RED}    Le token ne peut pas etre vide${NC}"
  read -rp "    Discord Bot Token: " DISCORD_TOKEN
done
echo ""

# 2. Domain (optional — enables HTTPS + TikTok)
echo -e "${BLUE}2/4${NC} Nom de domaine pour Postiz ${YELLOW}(optionnel)${NC}"
echo "    Exemple : postiz.mondomaine.com"
echo "    Si fourni, active HTTPS automatique (Let's Encrypt) + TikTok"
echo "    Laisse vide pour HTTP simple (pas de TikTok)"
read -rp "    Domaine [vide = HTTP]: " POSTIZ_DOMAIN
echo ""

# 3. Postiz port (only relevant without domain, but always used as fallback)
echo -e "${BLUE}3/4${NC} Port local pour Postiz (defaut: 4007)"
read -rp "    Port [4007]: " POSTIZ_PORT
POSTIZ_PORT="${POSTIZ_PORT:-4007}"
echo ""

# 4. Build POSTIZ_URL from domain or fallback to IP:port
if [[ -n "$POSTIZ_DOMAIN" ]]; then
  POSTIZ_URL="https://${POSTIZ_DOMAIN}"
  ENABLE_HTTPS=true
  echo -e "${GREEN}HTTPS active${NC} — Caddy obtiendra un certificat Let's Encrypt pour ${POSTIZ_DOMAIN}"
else
  echo -e "${BLUE}4/4${NC} URL publique de Postiz (sans domaine)"
  echo "    Exemple : http://51.255.195.30:4007"
  read -rp "    Postiz URL: " POSTIZ_URL
  while [[ -z "$POSTIZ_URL" ]]; do
    echo -e "${RED}    L'URL ne peut pas etre vide${NC}"
    read -rp "    Postiz URL: " POSTIZ_URL
  done
  ENABLE_HTTPS=false
fi
echo ""

# ─── Generate secrets ───
echo -e "${BLUE}Generation des cles...${NC}"
MASTER_ENCRYPTION_KEY=$(openssl rand -hex 32)
POSTIZ_JWT_SIGNING_KEY=$(openssl rand -hex 32)
echo -e "${GREEN}Cles generees${NC}"
echo ""

# ─── Create install directory ───
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

# ─── Download files ───
echo -e "${BLUE}Telechargement des fichiers...${NC}"
curl -fsSL "${RAW_URL}/docker-compose.prod.yml" -o docker-compose.yml
mkdir -p config/searxng
curl -fsSL "${RAW_URL}/config/searxng/settings.yml" -o config/searxng/settings.yml 2>/dev/null || true
curl -fsSL "${RAW_URL}/config/Caddyfile" -o config/Caddyfile 2>/dev/null || true
echo -e "${GREEN}Fichiers telecharges${NC}"

# ─── Generate .env ───
cat > .env << ENVEOF
# Le Chroniqueur — Generated by install.sh
# $(date)

DISCORD_TOKEN=${DISCORD_TOKEN}
MASTER_ENCRYPTION_KEY=${MASTER_ENCRYPTION_KEY}
POSTIZ_URL=${POSTIZ_URL}
POSTIZ_PORT=${POSTIZ_PORT}
POSTIZ_DOMAIN=${POSTIZ_DOMAIN}
POSTIZ_JWT_SIGNING_KEY=${POSTIZ_JWT_SIGNING_KEY}
ENVEOF

chmod 600 .env

# ─── Generate empty postiz-social.env ───
cat > postiz-social.env << SOCIALEOF
# Social media keys — filled automatically by the bot during onboarding
X_API_KEY=
X_API_SECRET=
TIKTOK_CLIENT_ID=
TIKTOK_CLIENT_SECRET=
INSTAGRAM_APP_ID=
INSTAGRAM_APP_SECRET=
LINKEDIN_CLIENT_ID=
LINKEDIN_CLIENT_SECRET=
SOCIALEOF

chmod 600 postiz-social.env

echo -e "${GREEN}Configuration generee${NC}"
echo ""

# ─── Start ───
echo -e "${BLUE}Demarrage des containers...${NC}"
if [[ "$ENABLE_HTTPS" == "true" ]]; then
  docker compose --profile https up -d
else
  docker compose up -d
fi

echo ""
echo -e "${GREEN}================================================${NC}"
echo -e "${GREEN}  Le Chroniqueur est installe !                 ${NC}"
echo -e "${GREEN}================================================${NC}"
echo ""
echo -e "  ${BLUE}Prochaines etapes :${NC}"
echo "  1. Invite le bot sur ton serveur Discord"
echo "     (lien d'invitation dans discord.com/developers)"
echo "  2. L'onboarding demarre automatiquement en DM"
echo ""
echo -e "  ${BLUE}Postiz :${NC} ${POSTIZ_URL}"
if [[ "$ENABLE_HTTPS" == "true" ]]; then
  echo -e "  ${BLUE}HTTPS :${NC}  Caddy (Let's Encrypt auto) pour ${POSTIZ_DOMAIN}"
  echo -e "  ${GREEN}TikTok : active (HTTPS disponible)${NC}"
else
  echo -e "  ${YELLOW}TikTok : desactive (pas de HTTPS)${NC}"
  echo "           Pour activer TikTok, relance avec un domaine."
fi
echo -e "  ${BLUE}Logs :${NC}   docker compose logs -f bot"
echo -e "  ${BLUE}Stop :${NC}   docker compose down"
echo -e "  ${BLUE}Update :${NC} docker compose pull && docker compose up -d"
echo ""
